import { type NextPage } from "next";
import Head from "next/head";
import GoalComponent from "./goalComponent";
import { signIn, signOut, useSession } from "next-auth/react";
import { api } from "../utils/api";
import CreateGoal from "./createGoalComponent";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-green-700 min-h-screen flex flex-col justify-center ">
        <p className="text-white text-center">
          {hello.data ? hello.data.greeting : "Loading tRPC query..."}
        </p>
        <GoalComponent />
        <AuthShowcase />
      </main>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();



  return (
    <div className="flex flex-col items-center justify-end gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.email}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
      {sessionData && <CreateGoal />}
    </div>
  );
};
